name: app_creative_val
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.7
  firebase_auth: ^4.9.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/


