// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYoWSubeFanI8xbLqo9aBPbTKZfe8lDw',
    appId: '1:271373791194:web:2c81fcfc43bfe620af5ae3',
    messagingSenderId: '271373791194',
    projectId: 'flutterapp-a3128',
    authDomain: 'flutterapp-a3128.firebaseapp.com',
    storageBucket: 'flutterapp-a3128.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_psssxYEb-zi7KJnxzxEg24I3fLJYIw',
    appId: '1:271373791194:android:2bde57dd4582fbf6af5ae3',
    messagingSenderId: '271373791194',
    projectId: 'flutterapp-a3128',
    storageBucket: 'flutterapp-a3128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQheY2hGP737gY4tdoLayvl7286C8uQ_g',
    appId: '1:271373791194:ios:fff55b2f9f558dbaaf5ae3',
    messagingSenderId: '271373791194',
    projectId: 'flutterapp-a3128',
    storageBucket: 'flutterapp-a3128.appspot.com',
    iosClientId: '271373791194-3vsllrnas3573qg0a4ferg6cjhdak4cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCreativeVal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQheY2hGP737gY4tdoLayvl7286C8uQ_g',
    appId: '1:271373791194:ios:e5ca358d52937dceaf5ae3',
    messagingSenderId: '271373791194',
    projectId: 'flutterapp-a3128',
    storageBucket: 'flutterapp-a3128.appspot.com',
    iosClientId: '271373791194-r9q39sqsfeadbeumj2cmb69rjoienj1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCreativeVal.RunnerTests',
  );
}
